# Generated by Django 4.2.7 on 2024-04-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviedata",
            name="typ",
            field=models.CharField(default="action", max_length=100),
        ),
    ]
